In [6]:
using POMDPs, POMDPTools, QuickPOMDPs, MCTS, DiscreteValueIteration, POMDPSimulators, POMDPModels, POMDPPolicies
using Distributions, Combinatorics, StaticArrays, D3Trees, Random
using FileIO, JLD2, TickTock

In [7]:
action=[(0,0), (0,1), (1,1)]

global Number_level = 4;
global Transition_matrix = [
    0.8571 0.1429 0.0    0.0;
    0.0    0.8571 0.1429 0.0;
    0.0    0.0    0.8    0.2;
    0.0    0.0    0.0    1.0
]
failure_penalty = -1200.0;
maintenance_penalty = -100.0;
setup_cost = -300.0;
normal_operation = 0.0;
system_penalty=-2000

-2000

In [8]:
function reward(s, a,s1=Number_level, rng=23)       #s is a vector of number units at each level and a is the number of units we will repair
    if a==1 #NO REPAIR, No SYSTEM FAILURE
         if s==Number_level
             r=system_penalty/(limit);
             return r
         else
             crd = Categorical(T[s,:,1]);
             s = rand(crd);
             r = normal_operation ;
              return r
             end
         end
     if a==2 # UNIT NOT REPAIRED UNLESS FAILURE BUT REPAIR IN SYSTEM
         if s==Number_level
              s=1
             crd = Categorical(T[s,:,1]);
             s = rand(crd);
             r=failure_penalty +  setup_cost/NumberUnits + normal_operation  ;
         return r
         else
             crd = Categorical(T[s,:,1]);
             s = rand(crd);
             r = normal_operation +  setup_cost/NumberUnits;
              return r
         end
     end
 
      if a==3 # UNIT REPAIRED AND MAINTENANCE IN SYSTEM NO SYSTEM FAILURE
         if s==Number_level
              s=1
             crd = Categorical(T[s,:,1]);
             s = rand(crd);
             r=failure_penalty +  setup_cost/NumberUnits + normal_operation  ;
         return r
         else
         s1=deepcopy(s)
         s=1
         r = maintenance_penalty +  setup_cost/NumberUnits
          crd = Categorical(T[s,:,1]);
             s = rand(crd);
             r+= normal_operation  ;
 #            r*=(s1/10);
        return r
 #         end
     end
     end
     
     if a==4 #UNIT REPAIRED AND MAINTENANCE IN SYSTEM with SYSTEM FAILURE FAILED UNIT TAKES Kth Component
         if s==Number_level
              s=1
             crd = Categorical(T[s,:,1]);
             s = rand(crd);
             r=failure_penalty +  setup_cost/NumberUnits + normal_operation + system_penalty/(limit) ;
         return r
         else
         s1=deepcopy(s)
         s=1
         r = maintenance_penalty +  setup_cost/NumberUnits
          crd = Categorical(T[s,:,1]);
             s = rand(crd);
             r+= normal_operation  ;
 #            r*=(s1/10);
        return r
 #         end
     end
     end
     
     end

reward (generic function with 3 methods)

In [9]:
s=1:Number_level;

In [10]:
(Transition_matrix)

4×4 Matrix{Float64}:
 0.8571  0.1429  0.0     0.0
 0.0     0.8571  0.1429  0.0
 0.0     0.0     0.8     0.2
 0.0     0.0     0.0     1.0

In [11]:
T=zeros(Number_level,Number_level,3);


In [12]:
T[:,:,1].=Transition_matrix;

In [13]:
T[:,:,2].=Transition_matrix;


In [14]:
for j in 1:Number_level
        T[j,:,3].=Transition_matrix[1,:];

        end
# for j in 1:10
#         T[j,:,3].=0.0
#     T[j,1,3]=1.0
#         end

In [15]:
T[Number_level,:,1].=0.0
T[Number_level,Number_level,1]=1.0
T[Number_level,:,2].=Transition_matrix[1,:]


4-element view(::Array{Float64, 3}, 4, :, 2) with eltype Float64:
 0.8571
 0.1429
 0.0
 0.0

In [16]:
# T[:,:,1].=T[:,:,1].*(repeat(.5:.5,10)-((10:1)./20))
# T[:,:,2].=T[:,:,2].*(repeat(.5:.5,10)-((10:1)./20))

In [17]:
T

4×4×3 Array{Float64, 3}:
[:, :, 1] =
 0.8571  0.1429  0.0     0.0
 0.0     0.8571  0.1429  0.0
 0.0     0.0     0.8     0.2
 0.0     0.0     0.0     1.0

[:, :, 2] =
 0.8571  0.1429  0.0     0.0
 0.0     0.8571  0.1429  0.0
 0.0     0.0     0.8     0.2
 0.8571  0.1429  0.0     0.0

[:, :, 3] =
 0.8571  0.1429  0.0  0.0
 0.8571  0.1429  0.0  0.0
 0.8571  0.1429  0.0  0.0
 0.8571  0.1429  0.0  0.0

In [18]:
T[:, :, 3]

4×4 Matrix{Float64}:
 0.8571  0.1429  0.0  0.0
 0.8571  0.1429  0.0  0.0
 0.8571  0.1429  0.0  0.0
 0.8571  0.1429  0.0  0.0

In [19]:
function explore()
    c=[1/3,1/3,1/3]

     crd = Categorical(c);
     return rand(crd)
    end 
function generative(s, a, rng=23)       # calculate true component-level reward r_i(s_i,a_i) nd get evolving states
    if a==1 # No replacement in system, no system failure
        # if s==Number_level
        #     r=system_penalty/(limit);
        #     return (sp=s, r=r)
        # else
            crd = Categorical(T[s,:,1]);
            s = rand(crd);
            r = normal_operation ;
             return (sp=s, r=r)
            # end
        end
    if a==2 # replacement in system, no system failure, corrective replacement for unit
        if s==Number_level
             s=1
            crd = Categorical(T[s,:,2]);
            s = rand(crd);
            #r=failure_penalty +  setup_cost/NumberUnits + normal_operation  ;
            r=failure_penalty  + normal_operation  ;
        return (sp=s, r=r)
        else
            crd = Categorical(T[s,:,2]);
            s = rand(crd);
            #r = normal_operation +  setup_cost/NumberUnits;
            r = normal_operation;
             return (sp=s, r=r)
        end
    end

     if a==3 # replacement in system, no system failure, preventive replacement for unit
        if s==Number_level
             s=1
            crd = Categorical(T[s,:,3]);
            s = rand(crd);
            #r=failure_penalty +  setup_cost/NumberUnits + normal_operation  ;
            r=failure_penalty + normal_operation  ;
        return (sp=s, r=r)
        else
        s1=deepcopy(s)
        s=1
        #r = maintenance_penalty +  setup_cost/NumberUnits
        r = maintenance_penalty
         crd = Categorical(T[s,:,3]);
            s = rand(crd);
            r+= normal_operation  ;
#            r*=(s1/10);
       return (sp=s, r=r)
#         end
    end
    end
    
    
    if a==4 # replacement in system, system failure occurs, preventive replacement for unit
        if s==Number_level
             s=1
            crd = Categorical(T[s,:,3]);
            s = rand(crd);
            #r=failure_penalty +  setup_cost/NumberUnits + normal_operation + system_penalty/(limit) ;
            r=failure_penalty+ normal_operation;
        return (sp=s, r=r)
        else
        s1=deepcopy(s)
        s=1
        #r = maintenance_penalty +  setup_cost/NumberUnits
        r = maintenance_penalty
         crd = Categorical(T[s,:,3]);
            s = rand(crd);
            r+= normal_operation;
#            r*=(s1/10);
       return (sp=s, r=r)
#         end
    end
    end

    end

generative (generic function with 2 methods)

In [20]:
function ValueIteration(S, T, γ, p1=0.01, d=100)
    Q=zeros((Number_level,4))
#     print(Q)
    V= zeros(Float64, (Number_level)).+1000
    diff=0
    i=0

    
   
    while i<=10000
#     while  i<=10000
    for s in 1:Number_level
       Threads.@threads for a in 1:4
#                 println(a)
#                 println(reward(s,a))
                if a>3
                Q[s,a]= (reward(s,a)) + γ*( sum(T[s,s1,3]*(V[s1]) for (s1) in 1:Number_level ))
                else
                Q[s,a]= (reward(s,a)) + γ*( sum(T[s,s1,a]*(V[s1]) for (s1) in 1:Number_level ))
                end
        end
#             print("here")

                p1=[exp(lamb*sum(Q[s,a3])) for a3 in 1:4]
                p1=p1./sum(p1)
#                  V[s]=sum(p1[1:3])*(p[1]*Q[s,1] + (p[2]+p[3])*max(Q[s,2],Q[s,3])) + sum(p1[4:(NumberUnits-limit+4)])*(sum(p2[b]*Q[s,b+3] for b in 1:(NumberUnits-limit+1)))
                 V[s]=(p1[1]*Q[s,1] + p1[2]*Q[s,2] +p1[3]*Q[s,3]+p1[4]*Q[s,4])
#             println(findmax(Q[s,1:4]))
#                 println(Q)
#                 V[s]=findmax(Q[s,1:4])[1]
                 
        end

        i+=1
        end
    return Q
    end

ValueIteration (generic function with 3 methods)

In [21]:

# function decison(Q, s)
#    a_final=[]
#    if Number_level in s
# #         print("hi")
#         d=(collect(Iterators.product((Q[s[i],2:3] for i in 1:NumberUnits)...)))
#         d1=(collect(Iterators.product((2:3 for i in 1:NumberUnits)...)))
#         min=-1e+10
#         opt=0
#         for (i,j) in enumerate(d)
#             if min < sum((j))
#                 min=sum((j))
#                 opt=i
#             end
#         end
#         return d1[opt]
#     end
#     q0=0.0
#     a_0=repeat(1:1,NumberUnits);
#     for i in 1:NumberUnits
#             q0+=Q[s[i],1]
#     end
#     d=(collect(Iterators.product((Q[s[i],2:3] for i in 1:NumberUnits)...)))
#     d1=(collect(Iterators.product((2:3 for i in 1:NumberUnits)...)))
# #     d[1]=a_0
# #     print("here")
# #     d1[1]=(1,1,1,1,1,1,1,1,1,1)
#     min=-1e+10
#     opt=0
#     for (i,j) in enumerate(d)
#         if i==1
#             if min < q0
#             min=q0
#             opt=i
#         end
#         elseif min < sum((j))
#             min=sum((j))
#             opt=i
#         end
#     end
#     if opt==1
#         return a_0
#     else
#         return d1[opt]
#     end
#     return opt
# end


function decison(Q, s,n=0.2)
   a_final=[]
    alpha=count(i->(i==Number_level), s) 
    alpha=deepcopy(limit)
   if count(i->(i==Number_level), s) >=limit
#         print("hi")
        count_1=0
        a_1=repeat(1:1,NumberUnits);
        for i in 1:NumberUnits
            a_1[i]=argmax(a->Q[s[i],a], [2,3])
            if s[i]==Number_level && alpha>0
                a_1[i]=4
                alpha=alpha-1
            end
        end
        return a_1
    end
    
    
    
    
    
    q0=0.0
    a_0=repeat(1:1,NumberUnits);
    for i in 1:NumberUnits
            q0+=Q[s[i],1]
    end
    a_1=repeat(1:1,NumberUnits);
    b=0
    for i in 1:NumberUnits
            a_1[i]=argmax(a->Q[s[i],a], [2,3])
            if s[i]==Number_level
                a_1[i]=3
            end
    end
    q1=0.0
    for i in 1:NumberUnits
            q1+=Q[s[i],a_1[i]]
    end
    
    if !(3 in a_1) 
        a_1=a_0
        q1=q0
    end
    
    
     if q0>q1
            return a_0
        else
#             print("HI")
            return a_1
            
        end
end

decison (generic function with 2 methods)

In [ ]:
using DataFrames
df= DataFrame(u=[],K=[],n=[],s=[],m=[],f=[],p=[],lamb=[],mean=[],std=[])
cost=[
   
    [0	-2000	-100	-1200 -2000]
] 

for units in [10, 20]
    for K in [4,6]
        
    global NumberUnits=convert(Int64,units)
        global limit=convert(Int64,K)
#      for lambda in [1,0.9,0.75,0.5,0.1,0.075,0.05,0.01,0.0075,0.005,0.0001]
     for lambda in [5,1,0.5, 0.1,0.05,1e-2,0.5e-2,1e-3,0.5e-3,1e-4,0.5e-4,1e-5,0.5e-5,1e-6,0.5e-6,1e-7,0.5e-7,1e-8]
#      for lambda1 in [0.0001,0.00001]
        
        global lamb=lambda
#         global lamb1=lambda1
            
            for c in cost
        tick()
   println(units)  
             print("K : ")
                    println(K)
    global normal_operation,setup_cost,maintenance_penalty,failure_penalty,system_penalty=c
     println(c)   

    global NumberUnits=units
     Q=ValueIteration(s,T,.95,3000)
#                 println(Q)
            println(isnan(Q[1,1]))
       if sum(isnan(Q[1,1]))>0.0
            continue
        end
tick()
trials=10000;
simsteps = 100;
results=zeros(trials)*0.1
Threads.@threads  for h in 1:trials
s=repeat(1:1,NumberUnits)
r1=[]
a1=[]   
r=repeat(1:1,NumberUnits)*1.0
 for k in 1:simsteps
    a =decison(Q,s)
            r2=0.0
#     print(s)
#                         println(a)
global failed_components = 0
for i in 1:NumberUnits
#             print(generative(s[i],a[i],234))
    if s[i] == Number_level
        failed_components += 1
    end
    s[i],r[i]=generative(s[i],a[i],234);
    r2+=r[i]
end 
if  (2 in a) ||(3 in a) ||(4 in a) 
    # if any replacement
        r2+=setup_cost
                end
if failed_components >= limit
    r2+=system_penalty
end
    s=s;
    append!(a1,a)
    append!(r1,r2)
end
rk=0
for i in 1:simsteps
    rk=0.95*rk+r1[simsteps-i+1]
end
#     println(rk)
    results[h]=rk
#     println(results)
end
println(units)
            print("k : ")
            println(limit)
println(lambda)

println(mean(results))

println(std(results))
pushfirst!(df,[units,limit,normal_operation,setup_cost,maintenance_penalty,failure_penalty,system_penalty,lamb,mean(results),std(results)])
        
tock()
end
    println("-------------------------")
end
end
end


10
K : 4


[ Info:  started timer at: 2025-12-09T18:55:06.363


[0 -2000 -100 -1200 -2000]
true
-------------------------
10

[ Info:  started timer at: 2025-12-09T18:55:10.315



K : 4
[0 -2000 -100 -1200 -2000]
true
-------------------------
10
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:55:11.627


true
-------------------------
10
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:55:12.864


false


[ Info:  started timer at: 2025-12-09T18:55:14.123


10
k : 4
0.1
-7941.884030575577
1508.197264190954
-------------------------
10
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            2.7376686s: 2 seconds, 737 milliseconds
[ Info:  started timer at: 2025-12-09T18:55:17.002


false


[ Info:  started timer at: 2025-12-09T18:55:18.316


10
k : 4
0.05
-7866.481673040983
1492.329164670127
-------------------------

[ Info:            2.0636599s: 2 seconds, 63 milliseconds



10
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:55:20.428


false


[ Info:  started timer at: 2025-12-09T18:55:21.691


10
k : 4
0.01
-8004.802123895571
1546.4764138217852
-------------------------
10
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            2.0850718s: 2 seconds, 85 milliseconds
[ Info:  started timer at: 2025-12-09T18:55:23.813


false


[ Info:  started timer at: 2025-12-09T18:55:25.105


10
k : 4
0.005
-9694.605870037136
1972.1813759346244
-------------------------
10
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            2.1237779s: 2 seconds, 123 milliseconds
[ Info:  started timer at: 2025-12-09T18:55:27.247


false


[ Info:  started timer at: 2025-12-09T18:55:28.541


10
k : 4
0.001
-9608.027710997745
1927.3207969138427
-------------------------
10
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            2.1825986s: 2 seconds, 182 milliseconds
[ Info:  started timer at: 2025-12-09T18:55:30.760


false


[ Info:  started timer at: 2025-12-09T18:55:32.070


10
k : 4
0.0005
-9543.57889775628
1881.1246901212287
-------------------------
10
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            2.1872318s: 2 seconds, 187 milliseconds
[ Info:  started timer at: 2025-12-09T18:55:34.295


false


[ Info:  started timer at: 2025-12-09T18:55:35.567


10
k : 4
0.0001
-9559.42335056267
1932.8935838690359
-------------------------
10
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            2.1902425s: 2 seconds, 190 milliseconds
[ Info:  started timer at: 2025-12-09T18:55:37.778


false


[ Info:  started timer at: 2025-12-09T18:55:39.052


10
k : 4
5.0e-5
-9336.993560354964
1866.3581954676802
-------------------------
10
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            2.2199584s: 2 seconds, 219 milliseconds
[ Info:  started timer at: 2025-12-09T18:55:41.288


false


[ Info:  started timer at: 2025-12-09T18:55:42.546


10
k : 4
1.0e-5
-9251.06434457215
1780.0362472420823
-------------------------
10
K : 

[ Info:            2.3178704s: 2 seconds, 317 milliseconds
[ Info:  started timer at: 2025-12-09T18:55:44.903


4
[0 -2000 -100 -1200 -2000]
false


[ Info:  started timer at: 2025-12-09T18:55:46.186


10
k : 4
5.0e-6
-9244.508209067113
1766.015866156832
-------------------------
10
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:             2.308932s: 2 seconds, 308 milliseconds
[ Info:  started timer at: 2025-12-09T18:55:48.542


false


[ Info:  started timer at: 2025-12-09T18:55:49.810


10
k : 4
1.0e-6
-9220.268862526103
1751.8379116830588
-------------------------
10
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            2.4834972s: 2 seconds, 483 milliseconds
[ Info:  started timer at: 2025-12-09T18:55:52.330


false


[ Info:  started timer at: 2025-12-09T18:55:53.593


10
k : 4
5.0e-7
-9211.484615950418
1759.5677868496948
-------------------------
10

[ Info:            2.2955203s: 2 seconds, 295 milliseconds
[ Info:  started timer at: 2025-12-09T18:55:55.939



K : 4
[0 -2000 -100 -1200 -2000]
false


[ Info:  started timer at: 2025-12-09T18:55:57.232


10
k : 4
1.0e-7
-9255.610103796897
1769.2582206148122
-------------------------
10
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            2.2032782s: 2 seconds, 203 milliseconds
[ Info:  started timer at: 2025-12-09T18:55:59.474


false


[ Info:  started timer at: 2025-12-09T18:56:00.751


10
k : 4
5.0e-8
-9223.790803069347
1762.719184469282
-------------------------
10
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            2.2606016s: 2 seconds, 260 milliseconds
[ Info:  started timer at: 2025-12-09T18:56:03.050


false


[ Info:  started timer at: 2025-12-09T18:56:04.315


10
k : 4
1.0e-8
-9234.536945280566
1754.4493521322456
-------------------------

[ Info:            2.2510429s: 2 seconds, 251 milliseconds



10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:56:06.593


true
-------------------------
10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:56:07.857


true
-------------------------
10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:56:09.106


true
-------------------------
10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:56:10.373


false


[ Info:  started timer at: 2025-12-09T18:56:11.617


10
k : 6
0.1
-7070.8831241465095
1307.5545134715494
-------------------------

[ Info:            2.2539626s: 2 seconds, 253 milliseconds



10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:56:13.912


false


[ Info:  started timer at: 2025-12-09T18:56:15.269


10
k : 6
0.05
-7072.007040845294
1311.8290408762375
-------------------------

[ Info:            2.1782513s: 2 seconds, 178 milliseconds



10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:56:17.486


false


[ Info:  started timer at: 2025-12-09T18:56:18.726


10
k : 6
0.01
-7242.622813780579
1363.8669670143413
-------------------------
10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            2.1440699s: 2 seconds, 144 milliseconds
[ Info:  started timer at: 2025-12-09T18:56:20.889


false


[ Info:  started timer at: 2025-12-09T18:56:22.189


10
k : 6
0.005
-8076.232686281788
1707.02731306516
-------------------------
10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            2.2106568s: 2 seconds, 210 milliseconds
[ Info:  started timer at: 2025-12-09T18:56:24.417


false


[ Info:  started timer at: 2025-12-09T18:56:25.649


10
k : 6
0.001
-8332.212850765274
1770.8783263882801
-------------------------
10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            2.1461422s: 2 seconds, 146 milliseconds
[ Info:  started timer at: 2025-12-09T18:56:27.821


false


[ Info:  started timer at: 2025-12-09T18:56:29.084


10
k : 6
0.0005
-8311.424623926767
1789.3814334284227
-------------------------
10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            2.2899486s: 2 seconds, 289 milliseconds
[ Info:  started timer at: 2025-12-09T18:56:31.413


false


[ Info:  started timer at: 2025-12-09T18:56:32.690


10
k : 6
0.0001
-8163.825280098036
1720.5329224773839
-------------------------
10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            2.1799288s: 2 seconds, 179 milliseconds
[ Info:  started timer at: 2025-12-09T18:56:34.887


false


[ Info:  started timer at: 2025-12-09T18:56:36.135


10
k : 6
5.0e-5
-8191.087001484588
1748.645722621093
-------------------------
10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            2.2587799s: 2 seconds, 258 milliseconds
[ Info:  started timer at: 2025-12-09T18:56:38.412


false


[ Info:  started timer at: 2025-12-09T18:56:39.729


10
k : 6
1.0e-5
-8204.54496079682
1745.3181456693314
-------------------------
10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            2.2889685s: 2 seconds, 288 milliseconds
[ Info:  started timer at: 2025-12-09T18:56:42.056


false


[ Info:  started timer at: 2025-12-09T18:56:43.354


10
k : 6
5.0e-6
-8181.101812311665
1726.986733705374
-------------------------
10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            2.1929348s: 2 seconds, 192 milliseconds
[ Info:  started timer at: 2025-12-09T18:56:45.582


false


[ Info:  started timer at: 2025-12-09T18:56:46.856


10
k : 6
1.0e-6
-8196.498799072264
1751.8385550741255
-------------------------
10

[ Info:            2.1354589s: 2 seconds, 135 milliseconds
[ Info:  started timer at: 2025-12-09T18:56:49.031



K : 6
[0 -2000 -100 -1200 -2000]
false


[ Info:  started timer at: 2025-12-09T18:56:50.283


10
k : 6
5.0e-7
-8214.935486863471
1736.7336663187255
-------------------------
10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            2.3328309s: 2 seconds, 332 milliseconds
[ Info:  started timer at: 2025-12-09T18:56:52.645


false


[ Info:  started timer at: 2025-12-09T18:56:53.922


10
k : 6
1.0e-7
-8156.126935467344
1709.5414977845458
-------------------------
10
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            2.3805548s: 2 seconds, 380 milliseconds
[ Info:  started timer at: 2025-12-09T18:56:56.323


false


[ Info:  started timer at: 2025-12-09T18:56:57.586


10
k : 6
5.0e-8
-8185.996635621407
1711.5292954817546
-------------------------


[ Info:             2.259636s: 2 seconds, 259 milliseconds
[ Info:  started timer at: 2025-12-09T18:56:59.880


10
K : 6
[0 -2000 -100 -1200 -2000]
false


[ Info:  started timer at: 2025-12-09T18:57:01.155


10
k : 6
1.0e-8
-8170.5132375247385
1701.5645692704998
-------------------------
20

[ Info:            2.2495734s: 2 seconds, 249 milliseconds
[ Info:  started timer at: 2025-12-09T18:57:03.433



K : 4
[0 -2000 -100 -1200 -2000]
true
-------------------------
20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:57:04.721


true
-------------------------
20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:57:05.963


true
-------------------------
20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:57:07.222


false


[ Info:  started timer at: 2025-12-09T18:57:08.477


20
k : 4
0.1
-15347.748159976885
2190.0321246766844
-------------------------
20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            4.3396018s: 4 seconds, 339 milliseconds
[ Info:  started timer at: 2025-12-09T18:57:12.846


false


[ Info:  started timer at: 2025-12-09T18:57:14.117


20
k : 4
0.05
-15338.815618153858
2208.8991490763237
-------------------------

[ Info:            4.2255598s: 4 seconds, 225 milliseconds



20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:57:18.369


false


[ Info:  started timer at: 2025-12-09T18:57:19.645


20
k : 4
0.01
-15716.110228293983
2320.3366124413847
-------------------------
20

[ Info:            4.2959234s: 4 seconds, 295 milliseconds
[ Info:  started timer at: 2025-12-09T18:57:23.964



K : 4
[0 -2000 -100 -1200 -2000]
false


[ Info:  started timer at: 2025-12-09T18:57:25.258


20
k : 4
0.005
-15474.282243640258
2251.6565131847383
-------------------------
20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            4.0690961s: 4 seconds, 69 milliseconds
[ Info:  started timer at: 2025-12-09T18:57:29.353


false


[ Info:  started timer at: 2025-12-09T18:57:30.634


20
k : 4
0.001
-15011.841200905355
2053.975308919994
-------------------------
20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            4.1232227s: 4 seconds, 123 milliseconds
[ Info:  started timer at: 2025-12-09T18:57:34.790


false


[ Info:  started timer at: 2025-12-09T18:57:36.068


20
k : 4
0.0005
-15109.640439494538
2052.136549854997
-------------------------
20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            4.2518974s: 4 seconds, 251 milliseconds
[ Info:  started timer at: 2025-12-09T18:57:40.344


false


[ Info:  started timer at: 2025-12-09T18:57:41.583


20
k : 4
0.0001
-15069.68034738195
2087.3957523298673
-------------------------

[ Info:            4.2067318s: 4 seconds, 206 milliseconds



20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:57:45.846


false


[ Info:  started timer at: 2025-12-09T18:57:47.155


20
k : 4
5.0e-5
-14819.910815139434
1960.529487470469
-------------------------
20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            4.0795875s: 4 seconds, 79 milliseconds
[ Info:  started timer at: 2025-12-09T18:57:51.264


false


[ Info:  started timer at: 2025-12-09T18:57:52.583


20
k : 4
1.0e-5
-14924.299565823487
1951.396426610843
-------------------------
20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            4.2303935s: 4 seconds, 230 milliseconds
[ Info:  started timer at: 2025-12-09T18:57:56.859


false


[ Info:  started timer at: 2025-12-09T18:57:58.163


20
k : 4
5.0e-6
-14880.179441453332
1942.314464650793
-------------------------
20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            4.1715626s: 4 seconds, 171 milliseconds
[ Info:  started timer at: 2025-12-09T18:58:02.361


false


[ Info:  started timer at: 2025-12-09T18:58:03.648


20
k : 4
1.0e-6
-14935.427710906577
1945.8969309535605
-------------------------
20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:            3.9772982s: 3 seconds, 977 milliseconds
[ Info:  started timer at: 2025-12-09T18:58:07.663


false


[ Info:  started timer at: 2025-12-09T18:58:08.924


20
k : 4
5.0e-7
-14926.352735151399
1928.9223395507202
-------------------------


[ Info:            4.0351104s: 4 seconds, 35 milliseconds
[ Info:  started timer at: 2025-12-09T18:58:12.977


20
K : 4
[0 -2000 -100 -1200 -2000]
false


[ Info:  started timer at: 2025-12-09T18:58:14.254


20
k : 4
1.0e-7
-14897.546710606926
1933.1772222321854
-------------------------
20
K : 4


[ Info:             3.922411s: 3 seconds, 922 milliseconds
[ Info:  started timer at: 2025-12-09T18:58:18.191


[0 -2000 -100 -1200 -2000]
false


[ Info:  started timer at: 2025-12-09T18:58:19.481


20
k : 4
5.0e-8
-14909.512640319967
1935.030062611196
-------------------------
20

[ Info:             4.204998s: 4 seconds, 204 milliseconds
[ Info:  started timer at: 2025-12-09T18:58:23.739



K : 4
[0 -2000 -100 -1200 -2000]
false


[ Info:  started timer at: 2025-12-09T18:58:25.026


20
k : 4
1.0e-8
-14911.617062021602
1936.072253987158
-------------------------
20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            3.9399165s: 3 seconds, 939 milliseconds
[ Info:  started timer at: 2025-12-09T18:58:28.992


true
-------------------------
20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:58:30.288


true
-------------------------
20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:58:31.593


true
-------------------------
20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:58:32.814


false


[ Info:  started timer at: 2025-12-09T18:58:34.034


20
k : 6
0.1
-13890.027795413223
1898.9268768421136
-------------------------
20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            3.9973283s: 3 seconds, 997 milliseconds
[ Info:  started timer at: 2025-12-09T18:58:38.056


false


[ Info:  started timer at: 2025-12-09T18:58:39.394


20
k : 6
0.05
-13873.388839274145
1921.035238761389
-------------------------
20

[ Info:            4.0933739s: 4 seconds, 93 milliseconds
[ Info:  started timer at: 2025-12-09T18:58:43.507



K : 6
[0 -2000 -100 -1200 -2000]
false


[ Info:  started timer at: 2025-12-09T18:58:44.795


20
k : 6
0.01
-14340.370259345656
2051.8836962917426
-------------------------
20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            4.0521598s: 4 seconds, 52 milliseconds
[ Info:  started timer at: 2025-12-09T18:58:48.873


false


[ Info:  started timer at: 2025-12-09T18:58:50.151


20
k : 6
0.005
-14226.84674825803
1999.857053661244
-------------------------
20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            4.0263327s: 4 seconds, 26 milliseconds
[ Info:  started timer at: 2025-12-09T18:58:54.204


false


[ Info:  started timer at: 2025-12-09T18:58:55.474


20
k : 6
0.001
-13913.153889545587
1902.8446417371606
-------------------------
20
K : 6


[ Info:            4.1821249s: 4 seconds, 182 milliseconds
[ Info:  started timer at: 2025-12-09T18:58:59.675


[0 -2000 -100 -1200 -2000]
false


[ Info:  started timer at: 2025-12-09T18:59:00.990


20
k : 6
0.0005
-13975.894127965352
1876.3647873722919
-------------------------

[ Info:            4.1599059s: 4 seconds, 159 milliseconds



20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:  started timer at: 2025-12-09T18:59:05.176


false


[ Info:  started timer at: 2025-12-09T18:59:06.491


20
k : 6
0.0001
-13980.871533948532
1887.6672753256228
-------------------------
20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            3.9995104s: 3 seconds, 999 milliseconds
[ Info:  started timer at: 2025-12-09T18:59:10.529


false


[ Info:  started timer at: 2025-12-09T18:59:11.789


20
k : 6
5.0e-5
-13935.864729413217
1799.9185844391734
-------------------------
20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            4.0664587s: 4 seconds, 66 milliseconds
[ Info:  started timer at: 2025-12-09T18:59:15.904


false


[ Info:  started timer at: 2025-12-09T18:59:17.203


20
k : 6
1.0e-5
-13917.328638985717
1834.7766819042727
-------------------------
20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            4.1819629s: 4 seconds, 181 milliseconds
[ Info:  started timer at: 2025-12-09T18:59:21.411


false


[ Info:  started timer at: 2025-12-09T18:59:22.681


20
k : 6
5.0e-6
-13886.24842057196
1821.0648642739538
-------------------------
20
K : 6
[0 -2000 -100 -1200 

[ Info:            4.0694609s: 4 seconds, 69 milliseconds
[ Info:  started timer at: 2025-12-09T18:59:26.789


-2000]
false


[ Info:  started timer at: 2025-12-09T18:59:28.082


20
k : 6
1.0e-6
-13943.58454353515
1832.1518290598754
-------------------------
20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            3.9893095s: 3 seconds, 989 milliseconds
[ Info:  started timer at: 2025-12-09T18:59:32.111


false


[ Info:  started timer at: 2025-12-09T18:59:33.352


20
k : 6
5.0e-7
-13925.653468267017
1826.2853519022233
-------------------------
20


[ Info:            4.1357215s: 4 seconds, 135 milliseconds
[ Info:  started timer at: 2025-12-09T18:59:37.506


K : 6
[0 -2000 -100 -1200 -2000]
false


[ Info:  started timer at: 2025-12-09T18:59:38.814


20
k : 6
1.0e-7
-13952.07572374714
1843.9301607450052
-------------------------
20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:            4.1050098s: 4 seconds, 105 milliseconds
[ Info:  started timer at: 2025-12-09T18:59:42.945


false


[ Info:  started timer at: 2025-12-09T18:59:44.213


20
k : 6
5.0e-8
-13954.393065673006
1801.653310283756
-------------------------
20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:             4.031631s: 4 seconds, 31 milliseconds
[ Info:  started timer at: 2025-12-09T18:59:48.273


false


[ Info:  started timer at: 2025-12-09T18:59:49.541


20
k : 6
1.0e-8
-13917.762367117506
1812.0346320062029
-------------------------


[ Info:            4.0679722s: 4 seconds, 67 milliseconds


LoadError: ParseError:
# Error @ ]8;;file://c:/Users/hhu98/OneDrive - UW-Madison/K-out-of-N revision Nov2025/Basic RL/In[22]#93:1\In[22]:93:1]8;;\
end
end
└─┘ ── invalid identifier

In [ ]:
df

In [ ]:
using CSV
CSV.write("ACW-MDP(case study).csv", df)

In [ ]:
Q